name: myapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: 
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_gemini: ^2.0.4
  google_generative_ai: ^0.4.1
  image_picker: ^1.1.1
  cached_network_image: ^3.3.0
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2
  responsive_grid_list: ^1.4.0
  intl: ^0.19.0
  english_words: ^4.0.0
  provider: ^6.0.0
  flutter_svg: ^2.0.10+1
  sqflite: ^2.0.0+3
  path: ^1.8.3
  camera: 
  path_provider: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/fonts/
  fonts:
    - family: Google Sans
      fonts:
        - asset: assets/fonts/GoogleSans-Regular copy.ttf
        - asset: assets/fonts/GoogleSans-Bold copy.ttf
        - asset: assets/fonts/GoogleSans-Medium copy.ttf
